# Generated by Django 3.0.4 on 2020-03-23 22:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('phoneNo', models.CharField(max_length=11)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=300, null=True, validators=[django.core.validators.RegexValidator(regex='.+www.facebook.com\\/[^\\/]+$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
