# Generated by Django 3.0.4 on 2020-03-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200321_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(default='user/static/profile_pics/default.jpg', upload_to='user/static/profile_pics'),
        ),
    ]
